site_name: Open Paging Server
site_url: https://docs.openpagingserver.org

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  logo: assets/images/logo.png
  favicon: assets/images/logo.png

extra_css:
  - stylesheets/extra.css

nav:
  - Main Website: https://www.openpagingserver.org
  - Welcome to Open Paging Server: index.md
  - Introduction:
      - Open Paging Server vs Commercial Products: introduction/commercial.md
  - Getting Started:
      - Install:
        - Linux (automatic): gettingstarted/install/linux.md
        - Linux (manual): gettingstarted/install/linux-man.md
      - First-time setup: gettingstarted/oobe.md

  - Administration:
      - Web:
        - Reverse proxies: admin/web/reverseproxy.md
      - Endpoints:
        - Cisco:
          - Overview: admin/endpoints/cisco/index.md
            - Enterprise: admin/endpoints/cisco/enterprise/index.md
              - Pre-requisites: admin/endpoints/cisco/enterprise/requisites.md
              - Connecting to CUCM: admin/endpoints/cisco/enterprise/cucm.md
site_dir: /var/www/opsdocs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
